project_id = "pgfeffykhanujyqymmir"

[functions.create-user]
verify_jwt = true

[functions.qz-sign]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-reopen-notification]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true

[functions.openai-tts]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true
