project_id = "pgfeffykhanujyqymmir"

[functions.create-user]
verify_jwt = true

[functions.qz-sign]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.send-reopen-notification]
verify_jwt = true
